using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using TankWatch.Domain; // For TankContext, Tank, TankTelemetry
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
 using System.Text.Json; 

namespace TankWatch.Worker
{   
    /// <summary>
    /// Worker is a background service that periodically generates and sends telemetry data for tanks.
    /// It retrieves tanks from the database, generates random telemetry data, and sends it via SignalR.
    /// </summary>
    public class Worker : BackgroundService
    {

        // IServiceProvider is used to create a scope for each execution
        // This allows us to resolve scoped services like TankContext
        private readonly IServiceProvider _services;

        // TelemetryService is used to send telemetry data to the API
        private readonly TelemetryService _telemetry;

        // constructor that takes IServiceProvider and TelemetryService
        // This allows us to resolve services from the DI container
        public Worker(IServiceProvider services, TelemetryService telemetry)
        {
            _services = services;
            _telemetry = telemetry;
        }

        // ExecuteAsync is the main method that runs in the background
        // It runs in a loop until the service is stopped or cancelled
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                try
                {
                    using var scope = _services.CreateScope();
                    var ctx = scope.ServiceProvider.GetRequiredService<TankContext>();
                    var tanks = ctx.Tanks.ToArray();
                    if (tanks.Any())
                    {
                        var rnd = Random.Shared;
                        var chosenTank = tanks[rnd.Next(tanks.Length)];
                        var newTelemetry = new TankTelemetry
                        {
                            Id = 0, // Auto-generated by database
                            Timestamp = DateTime.UtcNow,
                            Level = rnd.NextDouble() * 100,
                            Temperature = 20 + rnd.NextDouble() * 50,
                            Radiation = rnd.NextDouble() * 5,
                            Pressure = 10 + rnd.NextDouble() * 10,
                            TankId = chosenTank.Id
                            // Do not set Tank to avoid serialization issues
                        };

                        ctx.Telemetry.Add(newTelemetry);
                        await ctx.SaveChangesAsync(stoppingToken);
                        Console.WriteLine($"Added telemetry at {newTelemetry.Timestamp}");

                        // Create DTO for SignalR with tankName
                        var telemetryToSend = new
                        {
                            Id = newTelemetry.Id,
                            Timestamp = newTelemetry.Timestamp,
                            Level = newTelemetry.Level,
                            Temperature = newTelemetry.Temperature,
                            Radiation = newTelemetry.Radiation,
                            Pressure = newTelemetry.Pressure,
                            TankId = newTelemetry.TankId,
                            TankName = chosenTank.Name, // Matches frontend's Telemetry interface
                            Lat = chosenTank.Latitude,
                            Lng = chosenTank.Longitude
                        };

                        Console.WriteLine($"Preparing to send telemetry: {JsonSerializer.Serialize(telemetryToSend)}");
                        await _telemetry.SendTelemetryAsync(telemetryToSend, stoppingToken);

                        Console.WriteLine($"Sent telemetry via SignalR: {JsonSerializer.Serialize(telemetryToSend)}");
                    }
                    else
                    {
                        Console.WriteLine("No tanks found in database.");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error adding telemetry: {ex.Message}\nStackTrace: {ex.StackTrace}");
                }

                await Task.Delay(TimeSpan.FromSeconds(5), stoppingToken);
            }
        }
    }
}
